// Stock labels and contact copy for the TimTec catalog chatbot.
// CoA and SDS PDFs are generated by https://structure.timtec.org.
(function (root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  }
  root.TimTecCatalog = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const DOSES = ["1mg", "2mg", "5mg", "10mg", "15mg", "20mg", "30mg", "50mg"];

  // Older exports used a different city in the column name. Read that column
  // for the Yes/No value. The label functions never print that city.
  const STOCK_KEYS = [
    "In Stock Orlando, FL",
    "InStock_Orlando",
    "In Stock Kissimmee, FL",
    "InStock_Kissimmee",
    "In Stock Tampa, FL",
    "InStock_Tampa",
  ];

  const CONTACT = [
    "TimTec, LLC",
    "1950 East Irlo Bronson Memorial Highway, Suite 301",
    "Kissimmee, Florida 34744",
    "United States",
    "Phone: 302-292-8500",
    "Fax: 302-292-8520",
    "Email: timtec@timtec.org",
    "Website: www.timtec.org",
  ];

  const INQUIRY_TO = "timtec@timtec.org";
  const INQUIRY_CC = "ledger@timtec.org";
  const COA_PDF = "https://structure.timtec.org/api/coa/pdf?id=";
  const SDS_PDF = "https://structure.timtec.org/api/msds/pdf?id=";
  const ORLANDO_LEAD = "about 1 business day";
  const OVERSEAS_LABEL = "Extended overseas stock";
  const OVERSEAS_LEAD = "1-3 weeks";

  function libraryCode(raw) {
    const value = raw.Library ?? raw.library ?? raw.Catalog ?? raw.catalog ?? "";
    return String(value).trim().toUpperCase();
  }

  function isOrlandoLibrary(code) {
    return code === "A01" || code === "A02";
  }

  function isOverseasLibrary(code) {
    return code === "A03" || code === "A04" || code.startsWith("A03") || code.startsWith("A04");
  }

  function readStockRaw(raw) {
    for (const key of STOCK_KEYS) {
      const value = raw[key];
      if (value != null && String(value).trim() !== "") return value;
    }
    return "";
  }

  function stockYesNo(value) {
    if (value == null) return "";
    const text = String(value).trim().toLowerCase();
    if (!text) return "";
    if (["yes", "y", "true", "in stock"].includes(text)) return "Yes";
    if (["no", "n", "false", "out of stock", "unavailable", "not in stock"].includes(text)) return "No";
    const numeric = Number.parseFloat(text.replace(/[^\d.-]/g, ""));
    if (!Number.isNaN(numeric) && /\d/.test(text)) return numeric > 0 ? "Yes" : "No";
    return "";
  }

  function formatPurity(raw) {
    if (raw == null) return "N/A";
    const text = String(raw).trim();
    if (!text || text.toLowerCase() === "none" || text.toLowerCase() === "null") return "N/A";
    if (text.includes("%")) return text;
    const value = Number(text);
    if (!Number.isFinite(value)) return text;
    if (value > 0 && value <= 1) {
      const percent = Math.round(value * 1000) / 10;
      return `${percent}%`;
    }
    if (value > 1 && value <= 100) return `${value}%`;
    return text;
  }

  function formatMw(raw) {
    if (raw == null || raw === "") return "N/A";
    const value = Number(raw);
    if (!Number.isFinite(value)) return String(raw);
    return value.toFixed(2);
  }

  function displayPrice(raw) {
    if (raw == null) return "Request";
    const text = String(raw).trim();
    if (!text || text.toLowerCase().includes("request") || Number.isNaN(Number.parseFloat(text))) {
      return "Request";
    }
    return text.startsWith("$") ? text : `$${text}`;
  }

  function leadForLibrary(code, rawLead) {
    const text = rawLead == null ? "" : String(rawLead).trim();
    if (isOverseasLibrary(code)) {
      if (!text || /1 business day/i.test(text)) return OVERSEAS_LEAD;
      return text;
    }
    if (isOrlandoLibrary(code)) {
      if (!text || /1 business day/i.test(text)) return ORLANDO_LEAD;
      return text;
    }
    return text || "Confirm on quote";
  }

  function stockLabel(code, yesNo) {
    if (isOverseasLibrary(code)) return OVERSEAS_LABEL;
    if (isOrlandoLibrary(code)) {
      const shown = yesNo === "Yes" || yesNo === "No" ? yesNo : "Check availability";
      return `In stock (Orlando, Florida): ${shown}`;
    }
    return "Check availability";
  }

  function normalizeProduct(raw) {
    const code = libraryCode(raw);
    const yesNo = stockYesNo(readStockRaw(raw));
    const id = raw.TimTec_ID == null ? "" : String(raw.TimTec_ID).trim();
    const formula = raw["Brutto-formula"] ?? raw.Formula ?? raw.formula ?? "";
    return {
      id,
      smiles: raw.SMILES == null ? "" : String(raw.SMILES).trim(),
      iupac: raw.IUPAC == null ? "" : String(raw.IUPAC).trim(),
      formula: formula == null || formula === "" ? "N/A" : String(formula),
      molecularWeight: formatMw(raw["Molecular weight"] ?? raw.MolecularWeight),
      purity: formatPurity(raw["Purity %"] ?? raw.Purity),
      library: code,
      stock: stockLabel(code, yesNo),
      lead: leadForLibrary(code, raw["Lead Time"] ?? raw.LeadTime),
      prices: DOSES.map((dose) => ({
        dose,
        price: displayPrice(raw[`Price_${dose}`]),
      })),
    };
  }

  function isVirtualCollectionQuery(query) {
    const compact = String(query || "").trim().toLowerCase().replace(/[\s_]+/g, "");
    return compact === "mcl-5000" || compact === "mcl5000";
  }

  function searchCatalog(products, query, limit) {
    const max = limit == null ? 12 : limit;
    const q = String(query || "").trim().toLowerCase();
    if (!q || isVirtualCollectionQuery(q)) return { results: [], total: 0, capped: false, virtual: isVirtualCollectionQuery(q) };
    const exact = [];
    const partial = [];
    for (const product of products) {
      const id = product.id.toLowerCase();
      const smiles = product.smiles.toLowerCase();
      if (id === q || (smiles && smiles === q)) exact.push(product);
      else if (product.iupac && product.iupac.toLowerCase().includes(q)) partial.push(product);
    }
    const matches = exact.length ? exact : partial;
    return {
      results: matches.slice(0, max),
      total: matches.length,
      capped: matches.length > max,
      virtual: false,
    };
  }

  function coaUrl(id) {
    return COA_PDF + encodeURIComponent(id);
  }

  function sdsUrl(id) {
    return SDS_PDF + encodeURIComponent(id);
  }

  function inquiryMailto(product) {
    const subject = `TimTec inquiry ${product.id}`;
    const body = [
      `TimTec ID: ${product.id}`,
      `Library: ${product.library || "N/A"}`,
      `IUPAC: ${product.iupac || "N/A"}`,
      product.smiles ? `SMILES: ${product.smiles}` : "",
      "",
      "Amount of interest (mg):",
      "",
      "Please confirm availability, pricing, and lead time.",
    ].filter((line) => line !== "").join("\n");
    return `mailto:${INQUIRY_TO}?cc=${encodeURIComponent(INQUIRY_CC)}&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  }

  function catalogRequestUrl(search) {
    const params = new URLSearchParams(search || "");
    const requested = params.get("catalog");
    if (requested && /^[A-Za-z0-9_./-]+$/.test(requested) && !requested.includes("..")) {
      return requested;
    }
    return "./catalog/TimTec_CATALOG_SOURCE.json?v=194361";
  }

  return {
    DOSES,
    CONTACT,
    INQUIRY_TO,
    INQUIRY_CC,
    COA_PDF,
    SDS_PDF,
    ORLANDO_LEAD,
    OVERSEAS_LABEL,
    OVERSEAS_LEAD,
    formatPurity,
    formatMw,
    displayPrice,
    libraryCode,
    isOrlandoLibrary,
    isOverseasLibrary,
    stockYesNo,
    stockLabel,
    normalizeProduct,
    isVirtualCollectionQuery,
    searchCatalog,
    coaUrl,
    sdsUrl,
    inquiryMailto,
    catalogRequestUrl,
  };
});
